[build]
command = "npm run netlify:build"
publish = "public/"

[[plugins]]
package = "@netlify/plugin-gatsby"

[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "strict-origin-when-cross-origin"

